### ISSUE TITLE
PlayerRevive with SquareMap causes inability to respawn

### ISSUE THREAD

**Issue by AryaElendril** [CreativeMD/PlayerRevive#160]
[crashreport (2).txt](https://github.com/user-attachments/files/16119538/crashreport.2.txt)
Hi there!

I'm using TerraFirmaGreg for 1.20.1 and PlayerRevive_FORGE_v2.0.25_mc1.20.1, alongside SquareMap and am having issues any time someone is downed by an enemy and they become unable to click on a respawn button. I'm unsure if this is something that could be helped on the PlayerRevive side, but it looks like when someone is downed, their player ID might change and be causing issues.
	
Let me know if I can provide any more information! Thank you!

 The crash report shows as follows:
```
[05Jul2024 22:31:03.589] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Grumzar2011 is bleeding. Grumzar2011 had a chemical accident
[05Jul2024 22:31:05.558] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: [Not Secure] <froyo_xx> options, resource packs
[05Jul2024 22:31:07.542] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Grumzar2011 had a chemical accident
[05Jul2024 22:31:08.399] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: [Not Secure] <Flurben> oop
[05Jul2024 22:31:17.170] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: No xyz.jpenilla.squaremap.forge.ForgePlayerManager$SquaremapPlayerCapability for player Grumzar2011
	Index: 10
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon eventPlayerEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		2: NORMAL
		3: ASM: xaero.map.events.CommonEventsForge@27a5fb8f onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		4: ASM: xaero.pac.common.event.CommonEventsForge@4b69f40a onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		5: ASM: class tschipp.carryon.events.CommonEvents onClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1516/0x00000008017448d0@5ab47acf
		7: ASM: class net.mehvahdjukaar.moonlight.forge.MoonlightForge onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		8: ASM: xaero.common.events.CommonEventsForge@3fe2013c onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$1516/0x00000008017448d0@5c7e0d28
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1516/0x00000008017448d0@3ba3809e
		11: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@5b71c9d4 playerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		12: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@602136c1 playerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
java.lang.IllegalStateException: No xyz.jpenilla.squaremap.forge.ForgePlayerManager$SquaremapPlayerCapability for player Grumzar2011
	at TRANSFORMER/squaremap@1.2.0/xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$cap$3(ForgePlayerManager.java:114)
	at TRANSFORMER/forge@47.2.6/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at TRANSFORMER/squaremap@1.2.0/xyz.jpenilla.squaremap.forge.ForgePlayerManager.cap(ForgePlayerManager.java:114)
	at TRANSFORMER/squaremap@1.2.0/xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$setupCapabilities$2(ForgePlayerManager.java:66)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.6/net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1159)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:442)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1517)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1589)

[05Jul2024 22:31:17.173] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundClientCommandPacket@ad993dd, suppressing error
java.lang.IllegalStateException: No xyz.jpenilla.squaremap.forge.ForgePlayerManager$SquaremapPlayerCapability for player Grumzar2011
	at xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$cap$3(ForgePlayerManager.java:114) ~[squaremap-forge-mc1.20.1-1.2.0.jar%23318!/:?]
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[forge-1.20.1-47.2.6-universal.jar%23350!/:?]
	at xyz.jpenilla.squaremap.forge.ForgePlayerManager.cap(ForgePlayerManager.java:114) ~[squaremap-forge-mc1.20.1-1.2.0.jar%23318!/:?]
	at xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$setupCapabilities$2(ForgePlayerManager.java:66) ~[squaremap-forge-mc1.20.1-1.2.0.jar%23318!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:540) ~[forge-1.20.1-47.2.6-universal.jar%23350!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1159) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:442) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1517) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23345!/:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	```

**Comment by CreativeMD** [comment]
Hey, the log is full of errors from square map. I'm not sure if PlayerRevive is involved into this issue directly. Does the game crash or will it continue to run? If i understand it correctly, once the players bled out they cannot click on the respawn button?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. If the issue still persists please respond here.

**Comment by AndreyKrasnov06** [comment]
the issue still persists

```
Exception caught during firing event: No xyz.jpenilla.squaremap.forge.ForgePlayerManager$SquaremapPlayerCapability for player Dloiram
	Index: 12
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon eventPlayerEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		2: NORMAL
		3: ASM: class net.fabricmc.fabric.impl.entity.event.EntityEventHooks onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001841e721958@682149df
		5: ASM: xaero.common.events.CommonEventsForge@3ced9b8a onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		6: ASM: xaero.map.events.CommonEventsForge@257b1780 onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		7: ASM: com.github.alexthe666.citadel.server.CitadelEvents@1ca1b244 onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		8: ASM: class it.hurts.sskirillss.relics.init.CapabilityRegistry onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		9: ASM: class com.obscuria.obscureapi.network.PlayerDataCapability$EventBusHandlers clonePlayer(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		10: ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents onPlayerCloned(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		11: ASM: class com.enderio.base.common.enchantment.SoulBoundHandler reviveHandler(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001841e721958@70b75c4f
		13: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@57a76b9f playerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
java.lang.IllegalStateException: No xyz.jpenilla.squaremap.forge.ForgePlayerManager$SquaremapPlayerCapability for player Dloiram
	at TRANSFORMER/squaremap@1.2.0/xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$cap$3(ForgePlayerManager.java:114)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at TRANSFORMER/squaremap@1.2.0/xyz.jpenilla.squaremap.forge.ForgePlayerManager.cap(ForgePlayerManager.java:114)
	at TRANSFORMER/squaremap@1.2.0/xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$setupCapabilities$2(ForgePlayerManager.java:66)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1159)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:442)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1517)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[23дек.2024 16:01:10.543] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundClientCommandPacket@1b9cd418, suppressing error
java.lang.IllegalStateException: No xyz.jpenilla.squaremap.forge.ForgePlayerManager$SquaremapPlayerCapability for player Dloiram
	at xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$cap$3(ForgePlayerManager.java:114) ~[squaremap-forge-mc1.20.1-1.2.0.jar%23349!/:?]
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[forge-1.20.1-47.3.0-universal.jar%23378!/:?]
	at xyz.jpenilla.squaremap.forge.ForgePlayerManager.cap(ForgePlayerManager.java:114) ~[squaremap-forge-mc1.20.1-1.2.0.jar%23349!/:?]
	at xyz.jpenilla.squaremap.forge.ForgePlayerManager.lambda$setupCapabilities$2(ForgePlayerManager.java:66) ~[squaremap-forge-mc1.20.1-1.2.0.jar%23349!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:540) ~[forge-1.20.1-47.3.0-universal.jar%23378!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1159) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:442) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1517) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Why there is a "class net.fabricmc.fabric.impl.entity.event.EntityEventHooks" in stacktrace? I am using forge version of squaremap

**Comment by CreativeMD** [comment]
I do not see any relation to PlayerRevive here.
