### ISSUE TITLE
i took no damage

### ISSUE THREAD

**Issue by khaled2w** [CreativeMD/PlayerRevive#40]
Some days ago I was dying during a fall in Lava with some influence from the mob from another mod
The server was crashed for some reason
After restarting the server, the rescue screen appeared to me and tried to press the respawn button without response, I tried several times by logging out and back in vain.
I had to cancel the mod via mods folder in server to disabled
But after restarting the game I was never damaged.

`Time: 1/12/20 12:56 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.creativemd.playerrevive.server.PlayerReviveServer.kill(PlayerReviveServer.java:68)
	at com.creativemd.playerrevive.server.ReviveEventServer.playerLeave(ReviveEventServer.java:100)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1338_ReviveEventServer_playerLeave_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:580)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:388)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by khaled2w** [comment]
While trying to solve the problem and tried some ways, I found the solution by killing the player from the server control panel.
And everything returned to the same condition.
