### ISSUE TITLE
Server crash on launch 1.2.6

### ISSUE THREAD

**Issue by Foxgreat** [CreativeMD/PlayerRevive#5]
// I let you down. Sorry :(

Time: 11/14/17 12:17 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Multiple entries with same key: playerrevive=FMLMod:playerrevive{1.0} and playerrevive=FMLMod:playerrevive{1.0}. To index multiple values under a key, use Multimaps.index.
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:403)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:403)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zif000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 2.6.32-042stab120.19
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1134577512 bytes (1082 MB) / 2107113472 bytes (2009 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx3584M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2529

[crash-2017-11-14_00.17.55-server.txt](https://github.com/CreativeMD/PlayerRevive/files/1468004/crash-2017-11-14_00.17.55-server.txt)

**Comment by Foxgreat** [comment]
But i only have one of PlayerRevive on server.
![screenshot_1](https://user-images.githubusercontent.com/29230185/32742309-4461a2a0-c8d3-11e7-9a83-a135001f60a6.png)

**Comment by CreativeMD** [comment]
Just update to the newest version, it is fixed already.
