### ISSUE TITLE
Default Config Issue [1.18.1]

### ISSUE THREAD

**Issue by itsdinkd** [CreativeMD/PlayerRevive#78]
[10:24:50] [Worker-Main-10/WARN]: Invalid sounds.json in resourcepack: 'Mod Resources'
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: playerrevive:dream raid full
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.resources.sounds.Sound.<init>(Sound.java:20) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.resources.sounds.SoundEventRegistrationSerializer.m_119835_(SoundEventRegistrationSerializer.java:68) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.resources.sounds.SoundEventRegistrationSerializer.m_119830_(SoundEventRegistrationSerializer.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.resources.sounds.SoundEventRegistrationSerializer.deserialize(SoundEventRegistrationSerializer.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.resources.sounds.SoundEventRegistrationSerializer.deserialize(SoundEventRegistrationSerializer.java:16) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraft.util.GsonHelper.m_13771_(GsonHelper.java:514) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.util.GsonHelper.m_13767_(GsonHelper.java:532) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.sounds.SoundManager.m_5944_(SoundManager.java:69) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.client.sounds.SoundManager.m_5944_(SoundManager.java:39) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.18.1-20211210.034407-srg.jar%23343!:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by CreativeMD** [comment]
Fixed in the newest version. It failed to load a specific sound file.
